#!/usr/bin/env bash
# Changing the process port 8080 to 80 and creating zombie processes
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
